/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn; 


/**
 *
 * @author kedar
 */
public class tabla extends javax.swing.JFrame {
    ArrayList almacenarAlimento = new ArrayList();
    
    /**
     * Creates new form tabla
     */
    public tabla() {
        initComponents();
      
      // CENTRANDO VENTANA
      this.setLocationRelativeTo(null);
      // AJUSTE DEL TAMAÑO (ANCHO) DE LAS COLUMNAS 
      TableColumn columna;
      columna=jTable1.getColumnModel().getColumn(0);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
         
      columna=jTable1.getColumnModel().getColumn(1);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
      
      columna=jTable1.getColumnModel().getColumn(2);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
      
      columna=jTable1.getColumnModel().getColumn(3);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
      
      columna=jTable1.getColumnModel().getColumn(4);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
      
      columna=jTable1.getColumnModel().getColumn(5);
      columna.setPreferredWidth(120);
      columna.setMaxWidth(120);
      columna.setMinWidth(120);
     
//      EVITANDO QUE EL USUARIO PUEDA MOVER EL ORDEN DE LAS COLUMNAS
        jTable1.getTableHeader().setReorderingAllowed(false);
//        JTableHeader Theader = jTable1.getTableHeader();
//        Theader.setBackground(Color.red);
        
        //DANDO COLOR AL ENCABEZADO (FUENTE Y COLOR DE LETRA)
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD ,14));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(Color.red);
        jTable1.getTableHeader().setForeground(new Color(239,184,16));
        jTable1.setRowHeight(25);
        
        
        //
       
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsumac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_total = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        txtsumac.setText("jTextField1");
        txtsumac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsumacActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALIMENTOS GENERALES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pan Blanco", "260", "Pechuga de pollo", "108", "Aguacate", "200"},
                {"Arepa", "190", "Huevo Entero", "155", "Aceite de Semilas", "900"},
                {"Arroz blanco", "366", "Salchicha", "375", "Aceitunas", "115"},
                {"Arroz Integral", "350", "Ciervo", "375", "Nata", "337"},
                {"Harina de Maiz", "349", "Pechuga de Pavo", "111", "Linaza", "534"},
                {"Harina de Trigo", "341", "Salami", "507", "Yogurt Entero", "61"},
                {"Yuca", "148", "Jamón", "335", "Aceite de Oliva", "900"},
                {"Donut", "500", "Carne magra de cerdo", "143", "Brie", "263"},
                {"Galleta", "483", "Trucha", "96", "Camembert", "301"},
                {"Miel", "300", "Salmón", "137", "Cheddar", "381"},
                {"Acelgas", "30", "Atún Fresco", "158", "Edam", "306"},
                {"Cereza", "65", "Sardinas", "50", "Emmenrtal", "404"},
                {"Ciruela", "51", "Queso Mozarella", "245", "Gruyere", "393"},
                {"Durazno", "49", "Yogur Entero", "61", "Mozzarella", "245"},
                {"Fresa", "35", "Yogur Desnatado", "36", "Parmesano", "374"},
                {"Guayaba", "44", "Brie", "263", "Queso de Oveja", "380"},
                {"Kiwi", "46", "Queso Camembert", "301", "Requeson", "96"},
                {"Mandarina", "44", "Claras de Huevo", "53", "Roquefort", "413"},
                {"Mango", "61", "Huevo de Codorniz", "179", "Queso de Cabra", "173"},
                {"Manzana", "55", "Bistec de Ternera", "92", "Queso Fresco", "307"},
                {"Maracuyá", "66", "Hígado de Cerdo", "141", "Provolone", "392"},
                {"Melón", "25", "Higado Vacuno", "129", "Huevo Entero", "156"},
                {"Mora", "47", "Muslo de Pollo", "130", "Huevo de Codorniz", "179"},
                {"Naranja", "48", "Hamburguesa", "230", "Yema de Huevo", "341"},
                {"Papaya", "35", "Hamburguesa de Pollo", "153", "Cerdo carne grasa", "398"},
                {"Pera", "54", "Caballa", "170", "Lacón", "361"},
                {"Piña", "53", "Atún en Aceite", "288", "Pato", "288"},
                {"Sandía", "18", "Atún en Agua", "127", "Pavo Muslo", "186"},
                {"Uva", "68", "Calamar", "68", "Salami", "325"},
                {"Uva Pasa", "69", "Pulpo", "57", "Anguila", "264"},
                {"Zanahoria", "40", "Alubía", "316", "Arengue", "174"},
                {"Avena", "367", "Guisantes Secos", "304", "Atún Fresco", "158"},
                {"Pan Integral", "250", "Lenteja", "325", "Caballa", "170"},
                {"Platáno", "90", "Soja", "306", "Salmonete", "123"},
                {"Lechuga", "32", "Almendras", "499", "Anchoas", "175"},
                {"Col", "30", "Avellanacas", "625", "Arenque en Salmuera", "219"},
                {"Brócoli", "30", "Maní", "452", "Atún en Aceite", "288"},
                {"Pan francés", "300", "Piñon", "568", "Caviar en Lata", "262"},
                {"Pasta", "102", "Semilla de Sesamo", "563", "Sardinas en Lata", "268"},
                {"Papa ", "87", "Centeno", "350", "Langostino", "115"},
                {"Garbanzos", "130", "Semola", "361", "Garbanzos", "338"},
                {"Frijoles Negros", "77", "Chía ", "490", "Judias Blancas", "113"},
                {"Arvejas", "81", "Amaranto", "371", "Soja", "306"},
                {"Quinoa", "143", "Avena", "367", "Coco Fresco", "296"},
                {"Arepa Frita", "380", "Quinoa", "143", "Almendra", "499"},
                {"Mazorca", "106", "Yogurt Griego", "115", "Avellana", "625"},
                {"Tortilla", "52", "Baba ganush", "97", "Cacahuete", "452"},
                {"Centeno", "259", "Leche de Almendras", "40", "Nuez", "670"},
                {"Mijo", "350", "Leche de Vaca", "102", "Piñon", "568"},
                {"Castañas Secas", "209", "Pistachos", "562", "Pistacho", "600"}
            },
            new String [] {
                "Carbohidratos", "Calorias", "Proteinas ", "Calorias", "Grasas", "Calorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setFocusable(false);
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("ALIMENTOS GENERALES");

        jLabel2.setText("Calorías por 100 gramos");

        jButton1.setText("Seleccionar Alimento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_total.setBackground(new java.awt.Color(204, 255, 255));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jMenu2.setText("Menú");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        jMenuItem1.setText("Volver al inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        jMenuItem2.setText("Volver al menú");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Regresar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addGap(59, 59, 59)
                .addComponent(jButton3)
                .addGap(75, 75, 75)
                .addComponent(jButton2)
                .addGap(56, 56, 56)
                .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(182, 191, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
//      REGRESANDO A INICIO
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
//      REGRESANDO AL MENÚ
        Menu menu = new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //PARA SALIR
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
//        //LO QUE MANDO VALENTINA
            int filaseleccionada = jTable1.getSelectedRow();
            int columnaSeleccionada = jTable1.getSelectedColumn();
            String carbos = jTable1.getValueAt(filaseleccionada, columnaSeleccionada).toString();
           
            int carbohidratos = Integer.parseInt(carbos);
            almacenarAlimento.add(carbohidratos);
//            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsumacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsumacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsumacActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int suma1=0;
        for (int i = 0; i <almacenarAlimento.size(); i++) {
            int a = (int) almacenarAlimento.get(i);
            suma1 = a+suma1;
            String suma2 = String.valueOf(suma1);
            txt_total.setText(suma2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        txt_total.setText(null);
         int limpiar=0;
         for (int i = 0; i <almacenarAlimento.size(); i++) {
            int b = (int) almacenarAlimento.get(i);
            limpiar= (b+limpiar)*0;
            String botonLimpiar = String.valueOf(limpiar);
            txt_total.setText(botonLimpiar);
         almacenarAlimento.clear();
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    MenuTablas newframe = new MenuTablas();
    
    newframe.setVisible(true);
    
    this.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new tabla().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_total;
    private javax.swing.JTextField txtsumac;
    // End of variables declaration//GEN-END:variables
}
